import { WorkspaceHeader, WorkspaceUnavailable, workspaceAuth } from './workspace-shell';
import { money, nextAction, projectStep, type Mission } from '@/lib/workspace/model';
export async function WorkspaceDashboard({admin=false}:{admin?:boolean}) {
  const a=await workspaceAuth(admin);if(a.state!=='ready')return <WorkspaceUnavailable />;
  let mq=a.supabase.from('missions').select('*').order('updated_at',{ascending:false}).limit(100);
  if(!admin)mq=mq.eq('client_id',a.user.id);
  const [mr,pr,chat,ready,leads]=await Promise.all([mq,a.supabase.from('proposals').select('*').eq('status','envoyee').limit(100),a.supabase.from('messages').select('id,mission_id,body,sender_id,created_at').order('created_at',{ascending:false}).limit(12),a.supabase.from('missions').select('workflow_stage').limit(1),admin?a.supabase.from('leads').select('id,startup,status,first_name').order('created_at',{ascending:false}).limit(20):Promise.resolve({data:[],error:null})]);
  if(mr.error)return <WorkspaceUnavailable />;
  const missions=(mr.data||[]) as Mission[];const base=admin?'/admin':'/client';
  return <main className="workspace"><WorkspaceHeader email={a.user.email} admin={admin} name={a.profile.first_name||a.user.user_metadata?.full_name} avatar={a.user.user_metadata?.avatar_url||a.user.user_metadata?.picture} />
    <div className="workspace-title"><div><p className="section-index">{admin?'ADAM · ESPACE DE TRAVAIL':'VOTRE ESPACE AVEC ADAM'}</p><h1>{admin?'Qu’est-ce qui avance aujourd’hui ?':'Vos projets, au même endroit.'}</h1></div>{!admin&&!ready.error&&<a className="button button-dark" href="/client/nouveau">Présenter ma startup ↗</a>}</div>
    {ready.error&&<p className="workspace-notice" role="status">{admin?'La mise à jour Supabase 003 doit être appliquée pour activer les demandes et propositions centralisées.':'Les nouveaux dossiers sont en cours d’activation. Vous pouvez toujours contacter Adam depuis le site.'}</p>}
    <section className="workspace-next"><h2>{admin?'À faire maintenant':'Votre prochaine action'}</h2>{missions.length?<ul>{missions.filter(m=>m.status!=='termine').slice(0,5).map(m=><li key={m.id}><a href={`${base}/missions/${m.id}`}><strong>{m.title}</strong><span>{nextAction(m,admin)} →</span></a></li>)}</ul>:<p>{admin?'Aucun projet à traiter. Les demandes de vos clients apparaîtront ici.':'Présentez votre startup pour ouvrir un dossier et commencer une conversation avec Adam.'}</p>}</section>
    <div className="workspace-columns"><section><h2>{admin?'Dossiers clients':'Mes projets'}</h2>{!missions.length&&<p>Aucun dossier pour le moment.</p>}{missions.map(m=><a className="workspace-project" href={`${base}/missions/${m.id}`} key={m.id}><span className="workspace-tag">{projectStep(m)}</span><h3>{m.title}</h3><p>{m.estimated_delivery?`Livraison estimée : ${m.estimated_delivery}`:'Calendrier à définir ensemble'}</p><strong>Ouvrir le dossier →</strong></a>)}</section>
    <aside><section className="workspace-panel"><h2>Propositions en attente</h2>{pr.error?<p>Chargement indisponible.</p>:pr.data?.length?pr.data.map(p=><p key={p.id}>{p.mission_id?<a href={`${base}/missions/${p.mission_id}#proposition`}>{p.title} · {money(p.price_cents)} →</a>:<span>{p.title} · {money(p.price_cents)}</span>}</p>):<p>Aucune proposition en attente.</p>}</section>
    <section className="workspace-panel"><h2>Derniers messages</h2>{chat.error?<p>Chargement indisponible.</p>:chat.data?.length?chat.data.map(m=><article className="workspace-message-summary" key={m.id}><a href={`${base}/missions/${m.mission_id}#conversation`}><strong>{m.sender_id===a.user.id?'Vous':admin?'Client':'Adam'}</strong><p>{m.body.slice(0,140)}{m.body.length>140?'…':''}</p></a></article>):<p>Les échanges de vos projets apparaîtront ici.</p>}</section>
    {admin&&<section className="workspace-panel"><h2>Prospects récents</h2>{leads.data?.length?leads.data.map(l=><p key={l.id}><a href={`/admin/prospects/${l.id}`}><strong>{l.startup}</strong> · {l.status} → Lire la demande</a></p>):<p>Aucun prospect.</p>}</section>}</aside></div>
  </main>;
}
