import { notFound } from 'next/navigation';
import { WorkspaceHeader, WorkspaceUnavailable, workspaceAuth } from './workspace-shell';
import { WorkspaceForm } from './workspace-form';
import { money, nextAction, projectStep, uuid, type Mission } from '@/lib/workspace/model';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
export async function WorkspaceMission({id,admin=false}:{id:string;admin?:boolean}){
  const a=await workspaceAuth(admin);if(a.state!=='ready')return <WorkspaceUnavailable />;if(!uuid(id))notFound();
  const {data:m,error}=await a.supabase.from('missions').select('*').eq('id',id).single();
  if(error||!m||(!admin&&m.client_id!==a.user.id))notFound();const mission=m as Mission;
  const [chat,offers,payments]=await Promise.all([a.supabase.from('messages').select('id,sender_id,body,created_at').eq('mission_id',id).order('created_at',{ascending:false}).limit(100),a.supabase.from('proposals').select('*').eq('mission_id',id).neq('status','brouillon').order('created_at',{ascending:false}),a.supabase.from('payments').select('id,amount_cents,status').eq('mission_id',id)]);
  const paid=(payments.data||[]).filter(p=>p.status==='paye').reduce((n,p)=>n+p.amount_cents,0);
  const accepted=offers.data?.find(p=>p.id===m.proposal_id);
  return <main className="workspace"><WorkspaceHeader email={a.user.email} admin={admin} /><div className="workspace-title"><div><a href={admin?'/admin':'/client'}>← Tous les projets</a><h1>{m.title}</h1><span className="workspace-tag">{projectStep(mission)}</span></div><a className="button button-dark" href="#conversation">{admin?'Répondre au client':'Échanger avec Adam'} ↗</a></div>
    <section className="workspace-next"><h2>Prochaine étape</h2><p>{nextAction(mission,admin)}</p><p>{m.estimated_delivery?`Date estimée : ${m.estimated_delivery}`:'La date de livraison sera définie ensemble.'}</p></section>
    <nav className="workspace-sections" aria-label="Dans ce dossier"><a href="#brief">Le projet</a><a href="#conversation">Conversation</a><a href="#proposition">Proposition</a><a href="#paiements">Paiements</a></nav>
    <div className="workspace-columns"><div><section id="conversation" className="workspace-panel"><h2>Notre conversation</h2><p>Les {chat.data?.length===100?'100 derniers':'derniers'} messages de ce dossier. Les décisions importantes restent ici.</p>
      {chat.error?<p role="alert">Messages indisponibles. Actualisez la page.</p>:<ol className="workspace-chat">{[...(chat.data||[])].reverse().map(c=><li key={c.id} className={c.sender_id===a.user.id?'mine':''}><strong>{c.sender_id===a.user.id?'Vous':admin?'Client':'Adam'}</strong><time>{new Date(c.created_at).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</time><p>{c.body}</p></li>)}</ol>}
      <WorkspaceForm action="message" missionId={id} label="Envoyer mon message"><label>Votre message<textarea name="message" rows={4} maxLength={4000} required /></label></WorkspaceForm><a className="text-button" href={`?actualiser=${Date.now()}#conversation`}>Actualiser la conversation</a>
    </section><section id="proposition" className="workspace-panel"><h2>Proposition commerciale</h2>{offers.error?<p>La mise à jour Supabase est nécessaire pour activer les propositions centralisées.</p>:!offers.data?.length?<p>Je prépare une proposition après avoir compris votre besoin. Aucun montant n’est fixé pour le moment.</p>:offers.data.map(p=><article className="workspace-offer" key={p.id}><span className="workspace-tag">{p.status}</span><h3>{p.title}</h3><p>{p.description}</p><h4>Livrables et formats</h4><p>{p.deliverables}</p><dl><dt>Prix proposé</dt><dd>{money(p.price_cents)}</dd><dt>Acompte prévu</dt><dd>{money(p.deposit_cents||0)}</dd><dt>Solde prévu</dt><dd>{money(p.price_cents-(p.deposit_cents||0))}</dd><dt>Corrections incluses</dt><dd>{p.revisions??'À préciser'}</dd><dt>Délai</dt><dd>{p.estimated_delay||'À préciser'}</dd><dt>Valable jusqu’au</dt><dd>{p.valid_until||'À préciser'}</dd></dl><h4>Conditions</h4><p>{p.special_terms||'Aucune condition supplémentaire renseignée.'}</p>
      {!admin&&p.status==='envoyee'&&<WorkspaceForm action="answer" missionId={id} proposalId={p.id} label="Enregistrer ma réponse"><label>Ma réponse<NativeSelect name="answer" defaultValue="modifier"><NativeSelectOption value="modifier">Demander une modification</NativeSelectOption><NativeSelectOption value="accepter">Accepter cette proposition</NativeSelectOption><NativeSelectOption value="refuser">Refuser</NativeSelectOption></NativeSelect></label><label>Précisions<textarea name="note" maxLength={2000} rows={3} /></label><p>En choisissant « Accepter », vous acceptez le prix, les livrables et les conditions ci-dessus. Aucun paiement n’est déclenché par ce bouton.</p></WorkspaceForm>}
    </article>)}
    {admin&&!m.proposal_id&&!offers.error&&<details><summary>Préparer une nouvelle proposition</summary><WorkspaceForm action="propose" missionId={id} label="Envoyer cette proposition au client"><label>Prestation<input name="title" maxLength={120} required /></label><label>Description<textarea name="description" maxLength={3000} required /></label><label>Livrables et formats<textarea name="deliverables" maxLength={3000} required /></label><div className="form-row"><label>Prix total (€)<input name="price" inputMode="decimal" required /></label><label>Acompte (€)<input name="deposit" inputMode="decimal" required /></label></div><div className="form-row"><label>Séries de corrections<input name="revisions" type="number" min={0} max={50} required /></label><label>Délai annoncé<input name="delay" maxLength={120} required /></label></div><label>Fin de validité<input name="validUntil" type="date" required /></label><label>Conditions particulières<textarea name="terms" maxLength={4000} /></label><p>L’envoi remplace les propositions encore en attente, mais conserve leur historique.</p></WorkspaceForm></details>}
    </section></div><aside><section className="workspace-panel" id="brief"><h2>Le projet</h2><p className="workspace-prewrap">{m.brief}</p></section><section className="workspace-panel" id="paiements"><h2>Budget et paiements</h2>{!m.proposal_id?<p>Sur proposition. Aucun achat engagé.</p>:<><dl><dt>Prix accepté</dt><dd>{money(m.price_cents)}</dd><dt>Montant payé enregistré</dt><dd>{payments.error?'Indisponible':money(paid)}</dd><dt>Montant restant</dt><dd>{payments.error?'Indisponible':money(Math.max(0,m.price_cents-paid))}</dd><dt>Corrections prévues</dt><dd>{accepted?.revisions??'À préciser'}</dd></dl><p>Le paiement acompte/solde et le suivi des corrections sont en cours d’activation. Échangez avec Adam ici avant de procéder à un paiement.</p></>}</section></aside></div>
  </main>;
}
