import { beforeEach, expect, it, vi } from 'vitest';
const m=vi.hoisted(()=>({auth:vi.fn(),rpc:vi.fn(),single:vi.fn(),insert:vi.fn(),eq:vi.fn()}));
vi.mock('@/lib/supabase/server',()=>({requireRole:m.auth}));
import { POST } from '../../app/api/workspace/route';
import { cents, field, uuid, projectStep, type Mission } from './model';
const mid='11111111-1111-4111-8111-111111111111';
const client='22222222-2222-4222-8222-222222222222';
function request(body:unknown,origin='https://site.test'){return new Request('https://site.test/api/workspace',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});}
beforeEach(()=>{vi.resetAllMocks();m.rpc.mockResolvedValue({data:mid,error:null});m.single.mockResolvedValue({data:{id:mid,client_id:client},error:null});m.eq.mockReturnValue({single:m.single});m.insert.mockReturnValue({select:()=>({single:m.single})});m.auth.mockResolvedValue({state:'ready',user:{id:client},profile:{role:'client'},supabase:{rpc:m.rpc,from:()=>({select:()=>({eq:m.eq}),insert:m.insert})}});});
it('rejects cross-origin writes before reading identity',async()=>{expect((await POST(request({},'https://evil.test'))).status).toBe(403);expect(m.auth).not.toHaveBeenCalled();});
it('requires an authenticated account',async()=>{m.auth.mockResolvedValue({state:'anonymous'});expect((await POST(request({action:'request'}))).status).toBe(401);});
it('bounds the actual body without trusting content-length',async()=>{expect((await POST(request({text:'x'.repeat(17000)}))).status).toBe(413);expect(m.auth).not.toHaveBeenCalled();});
it('creates a request with server-owned identity, ignoring injected ids and roles',async()=>{const r=await POST(request({action:'request',title:'Projet',startup:'Startup',brief:'Produit',need:'Vidéo',client_id:'other',role:'admin'}));expect(r.status).toBe(200);expect(m.rpc).toHaveBeenCalledWith('workspace_request',{p_title:'Projet',p_startup:'Startup',p_brief:'Produit',p_need:'Vidéo'});});
it('refuses client proposal creation',async()=>{expect((await POST(request({action:'propose',missionId:mid}))).status).toBe(403);expect(m.rpc).not.toHaveBeenCalled();});
it('refuses a different client mission even if a database response returned it',async()=>{m.single.mockResolvedValue({data:{id:mid,client_id:'other'}});expect((await POST(request({action:'message',missionId:mid,message:'Hello'}))).status).toBe(404);expect(m.insert).not.toHaveBeenCalled();});
it('uses the authenticated sender for messages',async()=>{expect((await POST(request({action:'message',missionId:mid,message:' Bonjour ',sender_id:'admin'}))).status).toBe(200);expect(m.insert).toHaveBeenCalledWith({mission_id:mid,sender_id:client,body:'Bonjour'});});
it('rejects oversized messages',async()=>{expect((await POST(request({action:'message',missionId:mid,message:'x'.repeat(4001)}))).status).toBe(400);expect(m.insert).not.toHaveBeenCalled();});
it('uses a transactional RPC for acceptance, without browser prices',async()=>{expect((await POST(request({action:'answer',missionId:mid,proposalId:mid,answer:'accepter',note:'',price:1}))).status).toBe(200);expect(m.rpc).toHaveBeenCalledWith('workspace_answer',{p_mission:mid,p_proposal:mid,p_answer:'accepter',p_note:''});});
it('does not expose database internals on failure',async()=>{m.rpc.mockResolvedValue({error:{message:'private database details'}});const r=await POST(request({action:'request',title:'P',startup:'S',brief:'B',need:'N'}));expect(r.status).toBe(409);expect(await r.text()).not.toContain('private database');});
it('parses money in cents and refuses invalid prices',()=>{expect(cents('12,50')).toBe(1250);for(const v of ['-1','1e4','12.345','Infinity',{},''])expect(()=>cents(v)).toThrow();});
it('validates text and identifiers',()=>{expect(uuid(mid)).toBe(true);expect(uuid('../admin')).toBe(false);expect(()=>field({text:' '},'text',10)).toThrow();});
it('never labels a pre-proposal request as a paid mission',()=>{expect(projectStep({proposal_id:null,workflow_stage:'discussion'} as Mission)).toBe('Discussion avec Adam');});
