import 'server-only';
import type { ContactData } from './schema';
import { getServiceSupabase } from '@/lib/supabase/server';

const INTEGRATION = 'gmail_sender';
function required(name: string) { const value=process.env[name]?.trim(); if(!value) throw new Error(`GMAIL_CONFIG_${name}`); return value; }
function toBase64(bytes: Uint8Array) { let binary=''; for(const byte of bytes)binary+=String.fromCharCode(byte); return btoa(binary); }
function fromBase64(value: string) { const binary=atob(value); return Uint8Array.from(binary,(c)=>c.charCodeAt(0)); }
async function encryptionKey(){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(required('GMAIL_TOKEN_ENCRYPTION_KEY')));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt']);}
export async function encryptRefreshToken(token:string){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(token));return{encryptedSecret:toBase64(new Uint8Array(encrypted)),iv:toBase64(iv)};}
export async function decryptRefreshToken(secret:string,iv:string){const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(iv)},await encryptionKey(),fromBase64(secret));return new TextDecoder().decode(decrypted);}
export async function storeGmailAuthorization(ownerId:string,email:string,refreshToken:string){const supabase=getServiceSupabase();if(!supabase)throw new Error('GMAIL_STORAGE');const encrypted=await encryptRefreshToken(refreshToken);const{error}=await supabase.from('integration_credentials').upsert({name:INTEGRATION,owner_id:ownerId,email:email.toLowerCase(),encrypted_secret:encrypted.encryptedSecret,iv:encrypted.iv,updated_at:new Date().toISOString()});if(error)throw new Error('GMAIL_STORAGE');}
async function accessToken(){const supabase=getServiceSupabase();if(!supabase)throw new Error('GMAIL_STORAGE');const{data,error}=await supabase.from('integration_credentials').select('encrypted_secret,iv,email').eq('name',INTEGRATION).single();if(error||!data)throw new Error('GMAIL_NOT_CONNECTED');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:required('GMAIL_CLIENT_ID'),client_secret:required('GMAIL_CLIENT_SECRET'),refresh_token:await decryptRefreshToken(data.encrypted_secret,data.iv),grant_type:'refresh_token'})});if(!response.ok)throw new Error('GMAIL_TOKEN');const result=await response.json() as {access_token?:string};if(!result.access_token)throw new Error('GMAIL_TOKEN');return{token:result.access_token,email:data.email as string};}
function header(value:string){return value.replace(/[\r\n]+/g,' ').trim();}
function rawMessage(data:ContactData,sender:string){const subject=`Nouvelle demande STARTUP/AD — ${header(data.startup)}`;const text=['Nouvelle demande reçue depuis STARTUP/AD','',`Prénom : ${data.firstName}`,`Startup : ${data.startup}`,`Email : ${data.email}`,`Site / LinkedIn : ${data.website||'Non renseigné'}`,'','Projet :',data.project,'',`Besoin publicitaire : ${data.adType||'Non renseigné'}`,`Budget : ${data.budget||'Non renseigné'}`].join('\r\n');const message=[`From: STARTUP/AD <${header(sender)}>`,`To: ${header(sender)}`,`Reply-To: ${header(data.email)}`,`Subject: =?UTF-8?B?${toBase64(new TextEncoder().encode(subject))}?=`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',toBase64(new TextEncoder().encode(text))].join('\r\n');return toBase64(new TextEncoder().encode(message)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
export async function notifyGmail(data:ContactData){const auth=await accessToken();const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'},body:JSON.stringify({raw:rawMessage(data,auth.email)})});if(!response.ok)throw new Error(`GMAIL_SEND_${response.status}`);}
export async function saveThenNotifyGmail(data:ContactData,save:(data:ContactData)=>Promise<void>,notify=notifyGmail){await save(data);try{await notify(data);return{notification:'submitted' as const};}catch(error){const code=error instanceof Error&&/^GMAIL_[A-Z0-9_]+$/.test(error.message)?error.message:'GMAIL_UNKNOWN';console.warn('contact_notification',code);return{notification:'pending' as const};}}
